import { EditorThemeClasses } from "lexical";

const theme: EditorThemeClasses = {
    blockCursor: 'PlaygroundEditorTheme__blockCursor',
    hashtag: 'PlaygroundEditorTheme__hashtag',
    heading: {
        h1: 'PlaygroundEditorTheme__h1',
        h2: 'PlaygroundEditorTheme__h2',
        h3: 'PlaygroundEditorTheme__h3',
        h4: 'PlaygroundEditorTheme__h4',
        h5: 'PlaygroundEditorTheme__h5',
        h6: 'PlaygroundEditorTheme__h6',
    },
    image: 'editor-image',
    indent: 'PlaygroundEditorTheme__indent',
    inlineImage: 'inline-editor-image',
    link: 'PlaygroundEditorTheme__link',
    ltr: 'PlaygroundEditorTheme__ltr',
    mark: 'PlaygroundEditorTheme__mark',
    markOverlap: 'PlaygroundEditorTheme__markOverlap',
    paragraph: 'PlaygroundEditorTheme__paragraph',
    quote: 'PlaygroundEditorTheme__quote',
    rtl: 'PlaygroundEditorTheme__rtl',
    table: 'PlaygroundEditorTheme__table',
    tableCellEditing: 'PlaygroundEditorTheme__tableCellEditing',
    tableCellHeader: 'PlaygroundEditorTheme__tableCellHeader',
    tableCellPrimarySelected: 'PlaygroundEditorTheme__tableCellPrimarySelected',
    tableCellResizer: 'PlaygroundEditorTheme__tableCellResizer',
    tableCellSelected: 'PlaygroundEditorTheme__tableCellSelected',
    tableCellSortedIndicator: 'PlaygroundEditorTheme__tableCellSortedIndicator',
    tableResizeRuler: 'PlaygroundEditorTheme__tableCellResizeRuler',
    tableSelected: 'PlaygroundEditorTheme__tableSelected',
    text: {
        bold: 'PlaygroundEditorTheme__textBold',
        code: 'PlaygroundEditorTheme__textCode',
        italic: 'PlaygroundEditorTheme__textItalic',
        strikethrough: 'PlaygroundEditorTheme__textStrikethrough',
        subscript: 'PlaygroundEditorTheme__textSubscript',
        superscript: 'PlaygroundEditorTheme__textSuperscript',
        underline: 'PlaygroundEditorTheme__textUnderline',
        underlineStrikethrough: 'PlaygroundEditorTheme__textUnderlineStrikethrough',
    },
};

export default theme